### ISSUE TITLE
Analytics overview in dashboard

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#1]
Show Matomo statistics for a region in dashboard for back end users.

The Dashboard should display a chart of API calls per language and day during the last 30 days. The data can be fetched from the Matomo API. Each region has its own access token, that needs to be configured in the settings for the region. The setting is managed by the superadmins.

**Comment by Ponitac** [comment]
Thats my UI so far:
![grafik](https://user-images.githubusercontent.com/15608678/53950387-511ef480-40cc-11e9-99ac-f4c0be34a895.png)
Comments?

**Comment by svenseeberg** [comment]
I think its good. Simple and beautiful. The available formats are jpeg and csv, right?

**Comment by svenseeberg** [comment]
Note that this issue is about the dashboard integration, the general statistics issue is #8

**Comment by timoludwig** [comment]
Actually, this issue is not solved yet, right? Our dashboard is still empty... I think it's not much work to port the stuff from the statistics page to a card on the dashboard, but this issue should remain open until this is solved, right?
