### ISSUE TITLE
Image (JPEG/PNG) optimization via e.g. tinyjpg.com

### ISSUE THREAD

**Issue by benginoe** [Integreat/integreat-cms#118]
As we store pictures and deliver them throw the api, we should consider to optimize them in size for better network/access performance. We could do this with e.g. tinyjpg.com or other services like that. We should anyway store the original upload from the user but should process this and deliver the optimized version to the clients.

**Comment by svenseeberg** [comment]
I suggest to use local tools, i.e. optipng.
