### ISSUE TITLE
Pages: Considerations on how to deal with child pages when archiving the parent page

### ISSUE THREAD

**Issue by sascha11110** [Integreat/integreat-cms#132]
**Open questions:**

1. How do we deal with it if only the child pages are restored? (Ordering of pages)
2. How do we handle the archived status of child pages? Do we set the appropriate flag for each child page or do we simply derive the status from the parent pages?
3. What do we do if a child page has been archived in advance and then the parent page is archived? Do we restore all pages or only pages that have not been archived in advance?

**The following tasks resulted from the considerations so far:**

- [ ] In the list of archived pages and in the tree view, the child pages must also be displayed accordingly if the parent page has been archived [_only if we do not set the archived flag for all child pages_]

**Comment by svenseeberg** [comment]
The API pages endpoint only shows pages where the parent is also visible. See #538

Regarding the question: I would not change the status of children when changing the parent.

**Comment by timoludwig** [comment]
> Regarding the question: I would not change the status of children when changing the parent.

I agree. So for this issue to be closed, we just have to show non-archived pages in the archived page tree if their parent is archived. Otherwise, non-archived children of archived pages just completely vanish.
