### ISSUE TITLE
API: children of page endpoint

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#17]
Endpoint to get all children of a page. This must be compatible to Integreat API v3.

https://github.com/Integreat/cms/wiki/REST-APIv3-Documentation#children-of-a-post

@maxammann @Simple-codinger is this used by any current app? Otherwise this can be moved to another milestone.

**Comment by maxammann** [comment]
It's currently not used, but I would suggest to rethink the api and provide a different api for offline content loading and progressive content loading in the webapp.

**Comment by svenseeberg** [comment]
We still need to implement at least the API v3. We can discuss a newer API later.

**Comment by Simple-codinger** [comment]
For full backwards compatibility we also have to implement v0…

**Comment by svenseeberg** [comment]
@Simple-codinger can you provide information about how many installed apps are using which API version?

**Comment by Simple-codinger** [comment]
Currently all of the devices are using APIv0 because we still have some issues remaining in the  APIv3 Branch

**Comment by maxammann** [comment]
to be discussed in gdoc

**Comment by svenseeberg** [comment]
So we decided that this is not immediately necessary as there are no plans to change the API in the foreseeable future.

**Comment by svenseeberg** [comment]
Its now being used, but probably already implemented.
