### ISSUE TITLE
Show latest feedback in dashboard

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#2]
Show admins and content creators the latest feedback from app users in dashboard. This should be a list of the last ~5 messages. In some cases, the feedback only contains a thumbs up or down, in other cases it can contain a message. The title of the page or event concerned should be displayed as well and linked to the editing page.

Additional option: Add link that sends the message string to translate.google.com or deepl.com for translation. This can be useful if the feedback is given in a language the back end user does not understand. It is perfectly fine, if the link opens the translation website in a new tab. No need to fetch a translation via the API.

**Comment by timoludwig** [comment]
Regarding design choices: Please keep in mind that the dashboard consists of multiple separate info-boxes similar to the WordPress layout. So the feedback list in the dashboard should also only be a box, not the whole page:
![Screenshot_2020-12-01 Dashboard ‹ Testumgebung — WordPress](https://user-images.githubusercontent.com/16021269/100733598-b3567780-33ce-11eb-908f-65a1d11a8be8.png)
