### ISSUE TITLE
Production operation

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#209]
### Motivation

At the moment, the current packaging workflow leaves quite some tasks (e.g. collectstatic) which have to be performed on the production server. Also, some of our dependencies are not packaged for debian, so we'd have to re-package them ourselves if we wanted to make advantage of our cms being packaged as well.

### Proposed Solution

- Convert debian packaging to standard python packaging
- Add the possibility to pin the versions in the setup.py by generating a requirements.txt from the Pipfile.lock (via `pipenv lock -r > requirements.txt`)
- Perform collectstatic in packaging process
- Publish package on package registry (preferably PyPi)

#### Desired production installation
- Install Apache2
- Install PostgreSQL
- Execute:
  ```
  python3 -m venv .venv
  source .venv/bin/activate
  pip install integreat-cms
  ```
- Add database credentials, path to wsgi and path to static files to Apache config
- Start apache

#### Desired update process
- Stop apache
- `pip install --upgrade integreat-cms`
- Start apache

### Alternatives

- Drop packaging and use the dev setup (git pull & pipenv install) also for the production server

### Additional Context

- How to apply migrations? E.g. with post-install script: `cmdclass={'install': apply_migrations}`?
- How to make sure there are no inconsistencies in the static files or database while updating? E.g. stopping server before update?

**Comment by svenseeberg** [comment]
As we're now using CircleCI, we could probably create a build pipeline that delivers a .deb package into a Ubuntu PPA repository.

**Comment by timoludwig** [comment]
> As we're now using CircleCI, we could probably create a build pipeline that delivers a .deb package into a Ubuntu PPA repository.

Sounds very good! We can run this job every time we merge into the master branch and publish a new release.

**Comment by svenseeberg** [comment]
Another thought: The `settings.py` should reside in `/etc/integreat-cms/`.

**Comment by svenseeberg** [comment]
And if we are very lazy, we could include needed Python3 modules in the CMS .deb file.

**Comment by svenseeberg** [comment]
https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/modwsgi/

**Comment by svenseeberg** [comment]
Also relevant #603

**Comment by svenseeberg** [comment]
The integration of mod_wsgi and virtual environment works pretty well. We just need a "production deployment" script that creates and collects all static files and also executes the database migrations.
