### ISSUE TITLE
Pages list filter

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#240]
Add filter options to the pages overview. The following checkboxes should be available:

- [ ] "Translation is up-to-date" / "Übersetzung ist aktuell"
- [ ] "Translation is outdated" / "Übersetzung ist veraltet"
- [ ] "Translation is missing" / "Übersetzung fehlt"

Also, drag and drop should be deactivated when filters are applied.

**Comment by dkehne** [comment]
- No translation or needs an update
- Needs an update
- Archived

**Comment by Thomas125** [comment]
Is the information in the issue description about the need of an archived-filter still up to date?
We already have a button to change from active to archived pages.

**Comment by timoludwig** [comment]
> Is the information in the issue description about the need of an archived-filter still up to date?
> We already have a button to change from active to archived pages.

Good point, I guess not. The current separation of archived and non-archived pages will probably stay the same.

**Comment by timoludwig** [comment]
This is the current UI of wordpress:
![Screenshot_2021-01-09 Seiten ‹ Bad Tölz — WordPress](https://user-images.githubusercontent.com/16021269/104088022-11933780-5264-11eb-9172-998aff16a139.png)
The new solution should also provide this functionality. If you have ideas how to improve it, go on!
Also keep in mind the current implementation for the event filter.

**Comment by dkehne** [comment]
![104088022-11933780-5264-11eb-9172-998aff16a139](https://user-images.githubusercontent.com/4182469/104161297-ed199580-53f2-11eb-9892-6f473a8ed63b.png)

just from a functional perspektive :D what we need and what we do not need
