### ISSUE TITLE
Consistent list representations

### ISSUE THREAD

**Issue by florianhofhammer** [Integreat/integreat-cms#292]
~~Currently, the event list is somewhat broken and not displayed correctly (see figure 1 below). This should be fixed.~~
Apart from that, the different lists (especially for pages, events and pois) aren't rendered consistently. For example, they use different shades of grey for the table borders. It should be investigated in which points they really differ (apart from the given example) as well as those differences should be eliminated in order to have a consistent UI experience.

The work on this issue probably doesn't contain any logic fiddling and only requires changes to the templates (i.e. probably only changing some css classes of html elements).

![Screenshot_2021-03-18 Integreat Redaktionssystem(1)](https://user-images.githubusercontent.com/16021269/111649780-fc5afc00-8804-11eb-941a-1f148d480a85.png)
![Screenshot_2021-03-18 Integreat Redaktionssystem](https://user-images.githubusercontent.com/16021269/111649793-febd5600-8804-11eb-9b28-21d950b07c4a.png)

**Comment by timoludwig** [comment]
The list width is fixed in  #286. Not sure about the shadows though.

**Comment by florianhofhammer** [comment]
I'm sorry, I missed this fix. I'll lower the priority of this issue.

**Comment by svenseeberg** [comment]
Also, its worth noting that we have #172 still open. It would be cool to start creating meta classes for lists.

**Comment by ulliholtgrave** [comment]
This issue will be resolved, when we fully cover our CSS classes (as suggested in https://github.com/Integreat/integreat-cms/issues/172). Besides that, we solved a lot of the problems in the last merges by accident :)
