### ISSUE TITLE
Add page owner

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#314]
A page should optionally have a page owner, which is used to determine a logo beneath the content.
We could either solve this
 - via a user, which is linked to an organization
 - or directly via an organization

Which solution do you prefer? I think directly choosing an organization is a good idea. This way, we could make sure all members of an organization can change this page without adding multiple page editors/publishers.

**Comment by svenseeberg** [comment]
I vote for org as well.
