### ISSUE TITLE
Add Imprint form

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#39]
Add a form to edit the imprint.
This involves the form-model, form views and form templates.
This should be similar to the page form, so you can probably simply copy + paste existing code.

Depends on #357 :heavy_check_mark:

**Comment by ulliholtgrave** [comment]
This might be an issue that is related to the one you already solved @klinzo ,or?

**Comment by svenseeberg** [comment]
Definitely related, but not yet solved. We just have the model yet. The form is still needed.
