### ISSUE TITLE
Simple mode/expert mode

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#499]
### Motivation

Some functions are hard to use or more or less in a beta-state. To ensure that no additional training is needed after the migration of the CMS from WordPress to Django, we should disable these functions by default and only enable them on request.

Expert functions:
- Live Content / Mirror pages
- Do-Not-Translate-Tag
- Recurring Events
- Page-based permissions ("editors"/"publishers")
- XLIFF functions (XLIFF export and XLIFF import)
- Page filter

### Proposed Solution

Add two modes ("Simple mode"/"Expert mode"). Make some functionalities only accessible for ~regions~ users which have the "expert mode" activated.

As far as I can tell, the preferred place to save the expert mode enabled/disabled state is a field in the UserProfile model.

**Comment by timoludwig** [comment]
We could also think of this feature from a pure esthetics standpoint and just hide expert functions with css without bothering for permissions.

**Comment by melegiul** [comment]
![expert-mode](https://user-images.githubusercontent.com/47010475/106130565-cdf46500-6161-11eb-8e3c-50c37efcee94.png)

So I suggest the expert-modes interface looking like this. But now I see two options how to elaborate this.
1. I could take the existing database model ```config/configuration.py``` and create a key/value pair in the database for each settings entry like "expert-mode" and save the settings that way.
2. I could create a new database model + form called "user-settings" to make the settings to  a form like the already existing ones (page form, etc.) including form validation, ...

In both cases I would tend to sending asynchronous messages to server rather than a submission button, especially for the expert mode checkbox. The reason for that is, the user should be able to just set/unset the checkbox and update database instantly without taking care about the other settings entries and the submission button. 

@timoludwig @ulliholtgrave @svenseeberg Which one would you prefer?

**Comment by melegiul** [comment]
> We could also think of this feature from a pure esthetics standpoint and just hide expert functions with css without bothering for permissions.

Whats about using context variables and template tags instead of css. Like in the view:
```
context = {
// true or false
"expert-mode": models.settings.expert_mode
}
```
... and in the template:
```
{% if expert-mode %}
// only show up when expert mode is enabled
{% endif %}
```

**Comment by timoludwig** [comment]
> So I suggest the expert-modes interface looking like this. But now I see two options how to elaborate this.
> 
> 1. I could take the existing database model `config/configuration.py` and create a key/value pair in the database for each settings entry like "expert-mode" and save the settings that way.
> 
>2. I could create a new database model + form called "user-settings" to make the settings to  a form like the already existing ones (page form, etc.) including form validation, ...

I'm not 100% sure, but I tend to none of the above. The configuration model is more for global settings and I'm not even sure we really need this (since global settings can also go into settings.py) and since the `expert_mode` setting is just a boolean, I don't think we need another model for it. We can just add a new field to the `UserProfile` and manage it via the user form.

A different approach would be to handle it via permissions - Add one permission `can_use_expert_functions` and one role "Expert User" - but in this case, I strongly recommend to add permission checks to all views (also the ajax calls etc.), so that we don't "abuse" permissions for functionality, but still care about security. However, this is not a requirement for the expert mode (it should just simplify the UI, if users manage to "hack" the system to use expert functions, they are probably expert users anyway and there is no reason why they should not be allowed to do so). So all in all, I think I'd prefer a boolean field in the `UserProfile` model over permissions.

> In both cases I would tend to sending asynchronous messages to server rather than a submission button, especially for the expert mode checkbox. The reason for that is, the user should be able to just set/unset the checkbox and update database instantly without taking care about the other settings entries and the submission button.

I disagree. I don't see a reason why it should be necessary to update the database instantly (This setting won't get updated often, in most cases just once when creating the user). Moreover, our other forms are designed in a way that only something "final" happens, when you click a button which says "submit" or "do something". I think it's rather confusing for the users if the value changes in the second they toggle the checkbox.


> Whats about using context variables and template tags instead of css.
> ...
> {% if expert-mode %}
> // only show up when expert mode is enabled
> {% endif %}

In general, this is fine. But you have to make sure you also adapt the forms to these changes, otherwise the values will not remain unchanged, but just discarded every time a user without expert mode submits the form (in your PR  #648 e.g., I get the error `MultiValueDictKeyError at /augsburg/pages/de-de/1/edit 'mirrored_page_region'` when submitting the form). This errors you would easily circumvent if you just apply the css class "hidden" to all expert elements when the mode is disabled.

**Comment by melegiul** [comment]
> I'm not 100% sure, but I tend to none of the above. The configuration model is more for global settings and I'm not even sure we really need this (since global settings can also go into settings.py) and since the `expert_mode` setting is just a boolean, I don't think we need another model for it. We can just add a new field to the `UserProfile` and manage it via the user form.
> 
> A different approach would be to handle it via permissions - Add one permission `can_use_expert_functions` and one role "Expert User" - but in this case, I strongly recommend to add permission checks to all views (also the ajax calls etc.), so that we don't "abuse" permissions for functionality, but still care about security. However, this is not a requirement for the expert mode (it should just simplify the UI, if users manage to "hack" the system to use expert functions, they are probably expert users anyway and there is no reason why they should not be allowed to do so). So all in all, I think I'd prefer a boolean field in the `UserProfile` model over permissions.

Yes, I like the idea of a field at user profile also, because it can be updated more easy. I agree also that configuration model is the wrong place, I was not aware of their "global scope" until now, so the user field should be the right place.

**Comment by melegiul** [comment]
> I disagree. I don't see a reason why it should be necessary to update the database instantly (This setting won't get updated often, in most cases just once when creating the user). Moreover, our other forms are designed in a way that only something "final" happens, when you click a button which says "submit" or "do something". I think it's rather confusing for the users if the value changes in the second they toggle the checkbox.

I found it more comfortable to just switching the checkbox, but I'm also fine with an extra submit button, I will add this button just next to the checkbox.

**Comment by timoludwig** [comment]
> I found it more comfortable to just switching the checkbox, but I'm also fine with an extra submit button, I will add this button just next to the checkbox.

I wouldn't even add an extra button for this - just save the value when the entire user form is submitted.

**Comment by melegiul** [comment]
> > I found it more comfortable to just switching the checkbox, but I'm also fine with an extra submit button, I will add this button just next to the checkbox.
> 
> I wouldn't even add an extra button for this - just save the value when the entire user form is submitted.

Alright, so that means we should shift expert mode completely into the user form. I assumed that the expert mode should stay in the settings menu, but just change the model to UserProfile. What's about that? 

![user-form](https://user-images.githubusercontent.com/47010475/106357643-9a533f80-6307-11eb-80b1-8e27c2a70b16.png)

**Comment by timoludwig** [comment]
> Alright, so that means we should shift expert mode completely into the user form. I assumed that the expert mode should stay in the settings menu, but just change the model to UserProfile. What's about that? 


Yes, that sounds good! :+1:
