### ISSUE TITLE
RSS-Feed on the Region Dashboard

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#5]
### Motivation
As we are supporting a RSS-Feed on the current wordpress, we should deliver the same feature within our release. It should show the last blog entries from our website.
It not necessary to support a "already read" function. Showing the latest 5 news should be sufficient.

### Proposed Solution
It should be kind of equal to the current widget:
![grafik](https://user-images.githubusercontent.com/15608678/97785143-8af71580-1ba3-11eb-8159-36da574c65c5.png)

**Comment by timoludwig** [comment]
Check existing libraries for this task, e.g. [django-feed-reader](https://pypi.org/project/django-feed-reader/) or [feedparser](https://pypi.org/project/feedparser/).
