### ISSUE TITLE
Improve Translation Report View

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/integreat-cms#502]
### Motivation

_Update_: Due to our changed WebPack bundling, the translation report view doesn't work at all at the moment.
To fix this, have a look to how Chart.js is used in the [statistics view](https://github.com/Integreat/integreat-cms/blob/develop/src/frontend/js/analytics/statistics-charts.ts) and adapt the changes to the translation report accordingly.

Currently our View of the translation reports is kinda empty (as can be seen in the screenshot). The report just shows the number of pages were translations are up to date, not up to date or totally missing.
![grafik](https://user-images.githubusercontent.com/15608678/94277860-6d9eae00-ff4a-11ea-8e8a-04010b08047c.png)

### Proposed Solution
There are 2 things we can do to improve the situation:
* We should extend the shown information by adding a list of pages that belong to either category of the chart (up to date, outdated, translation missing). The relevant pages for each category should be shown while the mouse is hovering above a section of the bar. That means, while the mouse is hovering over "outdated translations" in English, a list of pages with outdated English translations should be shown.
* The layout of the graph should be changed to reduce the consumed space. This could be done by decreasing the height and mostly the width of the graph.

The result could look like this:
![Translation_Report_Changes](https://user-images.githubusercontent.com/15608678/94938788-9cc89880-04d1-11eb-84a6-d477b37159a2.png)

Additionally required:
- [ ] Total number of translations
- [ ] Number of word count in not-up-to-date translations (relevant for costs of translations)

**Comment by burnerlee** [comment]
Hello could i please work on this issue and make a PR in 1-2 days

**Comment by timoludwig** [comment]
> Hello could i please work on this issue and make a PR in 1-2 days

Sure! Since the issue description is a bit vague at the moment, we will add more details soon. But you can also propose your own ideas on improving the view if you want to.

**Comment by ulliholtgrave** [comment]
@burnerlee I updated the description of the issue to provide some additional information. We discussed internally the point of a possibility to view the respective pages, but would include this possibility to the list of pages (which can be found at /pages), but feel free to provide an additional visualization. We will definitely find a way of using it :)
Thanks for your effort :+1:

**Comment by burnerlee** [comment]
@ulliholtgrave do you have any slack community or something to get in touch with you. I would need help in understanding the scope of the issue and further things

**Comment by svenseeberg** [comment]
@burnerlee I'll send you an invite to our Slack space.

**Comment by ulliholtgrave** [comment]
@burnerlee You can just text me on slack or we may arrange a call. Whatever you prefer :)

**Comment by burnerlee** [comment]
We can talk on a call once and then I'll join your slack
