### ISSUE TITLE
Improve logging levels

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#507]
### Motivation

At the moment, some requests are logged very verbose, whereas other things aren't logged at all. This does not reflect the standards on logging levels: `debug`, `info`, `warning`, `error` and `critical`

### Proposed Solution

Change the logging levels to the values you think are reasonable and add debug information where it is missing.

E.g. logging similar to this: `logger.info("Form instantiated with data %s and instance %s", data, instance)` should rather be at the `debug` level.

Also improve the [settings file](https://github.com/Integreat/cms-django/blob/ae15187bc6e2526d554ada07936c66900dc9fd96/src/backend/settings.py#L214-L284) to make it easy to change the logging levels for all loggers at the same time without having to change many values.

**Comment by rexdivakar** [comment]
Please assign it to me i will work on it @timoludwig

**Comment by timoludwig** [comment]
> Please assign it to me i will work on it @timoludwig 

Amazing, thanks! Feel free to ask any questions if the issue description is unclear.

**Comment by timoludwig** [comment]
@rexdivakar Do you need more information about this issue or help in general?

**Comment by rexdivakar** [comment]
No will ask if needed @timoludwig

**Comment by timoludwig** [comment]
@rexdivakar Since you didn't seem to work on this issue, I unassigned you and took over the issue.
If you still want to contribute to our project, check out our other [good first issues](https://github.com/Integreat/integreat-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). Cheers!
