### ISSUE TITLE
Add shellcheck to circleci workflow

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#531]
### Motivation

The bash scripts in our repository are currently not part of any code style or correctness checks.

### Proposed Solution

We could add the tool [shellcheck](https://www.shellcheck.net/) to change this. Fortunately, it has already a pre-built [circleci orb](https://circleci.com/developer/orbs/orb/circleci/shellcheck) which can be easily added to our workflow. The specified directoy  of the job should be `dir: ./dev-tools`.

### Additional Context

Depending on the kind of errors/warnings the tool produces, the [dev-tools](https://github.com/Integreat/cms-django/tree/develop/dev-tools) might need a few changes to make them initially conform to shellcheck's standards.

**Comment by abhinand5** [comment]
Shall I give this a shot?

**Comment by timoludwig** [comment]
> Shall I give this a shot?

Sure, thanks! Since external PRs are not built in CircleCI, you might install shellcheck locally to test whether our bash scripts need manual adjustments. Is this possible for you?

**Comment by timoludwig** [comment]
Haha, kudos for your GitHub profile :muscle: I also love speed cubing :smile: 

![Screenshot_2020-10-11 abhinand5 - Overview](https://user-images.githubusercontent.com/16021269/95682278-b4480580-0be4-11eb-9e0a-4fb21ca4c19e.png)

**Comment by abhinand5** [comment]
> Is this possible for you?
Sure, @timoludwig no problem. 
> Haha, kudos for your GitHub profile 💪 I also love speed cubing 😄
Oh that's cool 😃 🙌

**Comment by timoludwig** [comment]
@abhinand5 Are you still interested in solving the issue? If not, please let us know so that others can take up the issue. Thanks!
