### ISSUE TITLE
Remove random short URL

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#539]
Currently we have to modes for short URLs implemented:

1. `s/<RANDOM_STRING>`: `PageTranslationAbstract` has an attribute to store a randomly generated 10 characters long string. This was introduced in PR #528 . This uses the additional `AbstractBasePageTranslation.short_url_id` attribute. 
2. `s/p/<ID>` we use the objects numeric ID in conjunction with a second part in the URL `/p/` to point towards pages. Events then get another URL, i.e. `s/e/<ID>`. ID in this case is the instance ID (integer) of a model in the database. This was introduced in PR ~#537~ #535.

I see no reason to hide our internal IDs. Additionally, the second pattern has no risk of collisions and is easier to read. Because option 1 depends on random strings, it always needs to be much longer to avoid collisions. And if we like, we could always convert numeric IDs to alphanumerical strings to reduce the length of the ID.

We decided that we do not need option 1. The code for option 1 can be removed.

**Comment by svenseeberg** [comment]
All opinions voiced say we should use option 2)

**Comment by timoludwig** [comment]
@mael-fosso @emmakemb @AminAlAit 

### Breakdown of what to do in this issue:

1. Remove URL to view `pages.expand_short_url` in [urls.py](https://github.com/Integreat/cms-django/blob/1a6c8ee1ab7fa6380660c62f88c835c39eaaedd4/src/cms/urls.py#L46)
2. Remove the view `expand_short_url` in [page_actions.py](https://github.com/Integreat/cms-django/blob/dfa7f189b16d62e79b4364ac28805f016f3d8421/src/cms/views/pages/page_actions.py#L114)
3. Remove field `short_url_id` from [abstract_base_page_translation.py](https://github.com/Integreat/cms-django/blob/dfa7f189b16d62e79b4364ac28805f016f3d8421/src/cms/models/pages/abstract_base_page_translation.py)
4. re-implement the property function `short_url` in [abstract_base_page_translation.py](https://github.com/Integreat/cms-django/blob/dfa7f189b16d62e79b4364ac28805f016f3d8421/src/cms/models/pages/abstract_base_page_translation.py#L102) so it returns the short URL of pattern 2 from above. You can use e.g. `reverse("expand_page_translation_id", short_url_id=self.id)` to get the url.
5. Fix the function `short_url_to_clipboard` in [copy-clipboard.js](https://github.com/Integreat/cms-django/blob/dfa7f189b16d62e79b4364ac28805f016f3d8421/src/cms/static/js/copy-clipboard.js#L1) so it copies the correct short url to the clipboard.
