### ISSUE TITLE
Add an "empty page" label to the TreeView

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/integreat-cms#567]
### Motivation
As we are introducing a label for pages, which are having an empty content, we should provide the same feature for the Django. The label should be shown by the following conditions...
... related region is not released.
... page is not mirroring content from another page.
... page has no children.
... page has an empty string as content.

### Proposed Solution
In the current system a wordpress filter is adding a label to the treeView if the conditions apply. This could of course be done in a different way in django. A possible solution could be a django filter/decorator to use it inside the django templating.
![grafik](https://user-images.githubusercontent.com/15608678/97785258-3607cf00-1ba4-11eb-98b1-005a34c82ac6.png)

**Comment by svenseeberg** [comment]
Implementing this should result in a reusable concept for other tags as well.
