### ISSUE TITLE
Fix icon fields for Events and POIs

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#574]
### Describe the Bug

In the Event and POI forms, the icon field is still a mock-up and doesn't work yet.

### Steps to Reproduce

1. Go to a region
2. Click on Events
3. Open any event
4. Try to add icon

### Expected Behavior

The file should be selectable and the file path should be saved in the model attribute after the form has been submitted.

### Actual Behavior

Nothing happens

### Additional Information

Just copy+paste the solution from the Page form which already works.

This is blocked by:
- [ ] #597 Adjust icon field in page form

**Comment by melegiul** [comment]
![Screenshot from 2020-11-18 12-22-03](https://user-images.githubusercontent.com/47010475/99524692-18ef4080-2999-11eb-9249-6838704cee6d.png)
What's about the styling of the ImageFieldWidget? Should we adjust "Current selected" and "Clear" elements first to fit better in the form before copy+paste?

**Comment by timoludwig** [comment]
> What's about the styling of the ImageFieldWidget? Should we adjust "Current selected" and "Clear" elements first to fit better in the form before copy+paste?

Yes, that's a very good idea! You can also use a custom widget like I suggested for the region icon if you want to.
