### ISSUE TITLE
Insert mailto: and tel: links automatically

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#587]
### Motivation

Whenever email addresses and phone numbers are used in the content, we should replace them with the according `mailto:` and `tel:` links.

### Proposed Solution

We could e.g. replace such strings in the clean-method of the content forms.

**Comment by ulliholtgrave** [comment]
The mailto feature can already be used by adding the autolink-Plugin (https://www.tiny.cloud/docs/plugins/opensource/autolink/) to the tinymce, but tel: is not supported. Therefore I am proposing extending the Plugin by the following RegEx to detect phone numbers:
/+?[0-9][0-9()-\s+]{4,20}[0-9]/

**Comment by svenseeberg** [comment]
I think we can make it much simpler: `([0-9\.\-\ \,\+\(\)]{3,30})`

We need to support numbers like:
* 110
* 1234
* +49 (0) 123 4567890
* 0049 123 4567890
* 0123 4567-890
* 01234567890
etc

IMHO there are no patterns we can rely on. There is only the limited character set that we can use to identify telephone numbers and the length. To my knowledge (and quick scan of https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) there are no TLDs with numbers only. That means we can safely assume that no domain can be numbers only, and therefore also no e-mail address.

**Comment by timoludwig** [comment]
> I think we can make it much simpler: `([0-9\.\-\ \,\+\(\)]{3,30})`

But we also have to think about false positives here. Do we really want to turn nearly every number into a phone number link? This would also affect e.g. years/dates (2021 or  2021-02-09 or 09.02.2021), normal numbers ("Almost 300,000 people from around 170 different nations"), typical float numbers (82.6), postal codes (86150 Augsburg), etc.
I'm afraid we clutter the whole content with phone links if we're too inclusive here.
Maybe a more complex regex is better than too many phone links? Or we define short phone numbers (110, 112) in a global setting and only match regular phone numbers with the regex? Or we ask the user every time we automatically convert a number into a phone number link?

**Comment by svenseeberg** [comment]
Okay, sorry. I understood that this is about recognizing user defined links as telephone numbers. In this case I think this issue should move to the additional features milestone.
