### ISSUE TITLE
Dynamic internal link target suggestions

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#590]
### Motivation

When adding internal links, we should dynamically suggest targets while typing.
Searching for page/event/poi titles should be possible as well slugs.

### Proposed Solution

Perform the dynamic search via AJAX. Also have a look at similar implementations, e.g. the dynamic POI suggestions in the event form.

**Comment by david-venhoff** [comment]
Should the event handler that makes the ajax calls be active in the editor or just in the `insert/link` prompt? If the event handler would just run in the `insert/link` prompt, it might make sense to just preload the available links, maybe roughly like that:
![grafik](https://user-images.githubusercontent.com/78504586/123636215-e1911e00-d81c-11eb-8864-1ff7fcb7dfb7.png)

What do you think about this approach?

**Comment by timoludwig** [comment]
I think in this case, we have to make the behavior somewhat similar to wordpress, otherwise the municipalities might be confused after the migration. This means, the suggestions need to be active in both cases, when marking text in the editor and when inserting a completely new link. Also, the suggestions should adapt to the text the user is typing, not only listing all available options. I'm not sure how it works in wordpress, it seems like not only the titles, but also the content of the targets are searched and suggested. For reference, here the inline suggestion of wordpress:
![Screenshot 2021-06-28 at 14-46-17 Seite bearbeiten ‹ Nürnberg — WordPress](https://user-images.githubusercontent.com/16021269/123641045-1b185800-d822-11eb-8e9d-3da6a333e1e4.png)
![Screenshot 2021-06-28 at 14-48-19 Seite bearbeiten ‹ Nürnberg — WordPress](https://user-images.githubusercontent.com/16021269/123641053-1e134880-d822-11eb-8a36-0172d1eb7de7.png)
And here the design of the "insert link"-promt:
![Screenshot 2021-06-28 at 14-49-29 Seite bearbeiten ‹ Nürnberg — WordPress](https://user-images.githubusercontent.com/16021269/123641370-7cd8c200-d822-11eb-85f5-4f02a60b7843.png)
Does that help? Do you think that's doable? The design doesn't have to be 100% identical, but the workflow of inserting internal links should roughly stay the same.
Since at the moment, we just have the prompt, even if inline text is selected for a link, I think it's ok to start with that and only implement the small inline suggestion box if needed.

**Comment by david-venhoff** [comment]
I think the link dialog functionality should be doable if I replace the link plugin with a custom plugin. Unfortunately this is my first time working with tinymce, so do you know of another/better way to achieve this?
It should be fine if not, but it would require re-implementing some of the functionality provided by the link plugin.

**Comment by timoludwig** [comment]
Sorry, I don't know much about tinymce plugins either, so I don't know if there is a better way. :unamused: 
E.g. our existing [autolink plugin](https://github.com/Integreat/integreat-cms/blob/develop/src/frontend/js/tinymce-plugins/autolink_tel/plugin.js) is also mostly copied+pasted, so I think it's fine to copy and replace the official link plugin. If you want to, you can also have a look at the [custom wordpress link plugin](https://github.com/Integreat/cms/blob/develop/wp-includes/js/tinymce/plugins/wplink/plugin.js), maybe there are also a few lines which can be copied...
