### ISSUE TITLE
Docstrings of feedback API not in documentation

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#595]
### Describe the Bug

In the [feedback API documentation](https://integreat.github.io/integreat-cms/autogenerated/api.v3.feedback.html), all view functions which are decorated with the [feedback_handler](https://integreat.github.io/integreat-cms/autogenerated/api.html#api.decorators.feedback_handler) are missing in the documentation, although their docstrings are fine.

### Steps to Reproduce

1. Go to the [feedback API documentation](https://integreat.github.io/integreat-cms/autogenerated/api.v3.feedback.html)
2. See missing docu (only internal functions are listed)

### Expected Behavior

The docstrings of the feedback api view functions should appear in the docu

### Actual Behavior

They are missing

### Additional Information

I assume this is because the decorator is used without [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps) which causes the decorated functions loose its meta information.

**Comment by david-venhoff** [comment]
Looks like the links are broken. I assume the documentation got moved to [there](https://integreat.github.io/integreat-cms/ref/api.v3.feedback.html)?
