### ISSUE TITLE
Improve "No Translate" button in TinyMCE

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#596]
In Wordpress we have a TinyMCE plugin that allows marking text with `<span translate="no">` tags. This functionality is very basic and does not working when spanning several other HTML Tags. A better implementation in Django would be cool. If this is programmed as a normal TinyMCE plugin, this could probably be backported to the current Wordpress plugin.

**Comment by timoludwig** [comment]
We already have a no-translate button which inserts the span. However, it does not yet work across multiple tags, so I'll leave this issue open to improve the functionality.
