### ISSUE TITLE
Chat for authors

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#6]
Create a chat that can be used to communicate between CMS users. It should be possible to create different channels, for example within one site, or a global chat. If messages are new (unread), they should be highlighted. A timestamp and the sender name should be displayed besides the message.

The chat should be integrated in the Dashboard.

**Comment by timoludwig** [comment]
Before this feature is implemented, it should be evaluated whether there is an open source solution which can be integrated without much effort.
