### ISSUE TITLE
Python module path of integreat-cms not correct

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#603]
### Describe the Bug

When installing the package as non-editable (with `pipenv run pip install .` instead of `pipenv run pip install -e .`), the sub-packages get installed separately without a parent integreat-cms package:

### Steps to Reproduce

```
$ pipenv run pip install .
$ pipenv run python
>>> import importlib
>>> importlib.import_module("integreat-cms")
ModuleNotFoundError: No module named 'integreat-cms'
>>> import cms
>>> cms
<module 'cms' from '/home/timo/integreat/integreat-cms/.venv/lib/python3.7/site-packages/cms/__init__.py'>
```

### Expected Behavior

I expect the integreat-cms to be a separate package with contains the sub-packages like cms, api etc.

### Actual Behavior

The sub-packages cms, api etc. get installed at the top-level of the /lib directory of the environment.

### Additional Information

The simplest fix for this might be to rename our "src" directory (again -.-) to "integreat-cms" and place an `__init__.py` inside.
Alternatively, we could add "integreat-cms" as symlink or fix the path in the packaging script by e.g. renaming the src directory, package it and rename it back...

**Comment by svenseeberg** [comment]
Just one question: Do we need to have everything in one module? AFAICT there is only one "hard" reason I can think of: name collisions for our apps: api, cms and backend. Beyond that, everything should be okay, right?

**Comment by timoludwig** [comment]
> Just one question: Do we need to have everything in one module? AFAICT there is only one "hard" reason I can think of: name collisions for our apps: api, cms and backend. Beyond that, everything should be okay, right?

exactly, I think it's just bad practise and name collusions, the package should still work.

**Comment by timoludwig** [comment]
I did some research about [best](https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure) [practises](https://hynek.me/articles/testing-packaging/) [of](https://github.com/pypa/packaging.python.org/issues/320#issuecomment-495990983) [python](https://stackoverflow.com/questions/49589082/pytest-python-src-layout) [projects](https://www.youtube.com/watch?v=sW1qUZ_nSXk), and it seems to me, that the following layout would reflect those results:
```
integreat-cms
├─ src
│  └─ integreat_cms
│     ├─ __init__.py
│     ├─ api/
│     ├─ backend/
│     ├─ cms/
│     └─ ...
├─ tests
│  └─ ...
└─ setup.py
```
Additionally, we could think about renaming `backend` to `core` to make it more obvious that this is the main entry point containing all settings etc...

**Comment by svenseeberg** [comment]
Agreed, also about `core`.
