### ISSUE TITLE
Use currently_in_translation flag

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#618]
### Motivation

Make use of the `currently_in_translation` flag in the content translation models.

### Proposed Solution

- [x] Set `currently_in_translation` flag when XLIFF is exported
- [x] Unset `currently_in_translation` flag when XLIFF is imported
- [x] Add possibility to manually unset `currently_in_translation` flag if translation process is cancelled
- [x] Show new icon for translations if the `currently_in_translation` flag is set (to make sure it is not shown as "outdated" anymore)
- [x] Show warning if a page is edited while the `currently_in_translation` flag is set (**optional/open debate**)

**Comment by timoludwig** [comment]
@melegiul as discussed in Mattermost, when xliffs are exported for a non-existing translation, we should **not** create an empty translation just to set the "currently in translation" flag. The reason behind this is that often times, xliffs are just exported to get an offer from the translation service, but if that's too expensive, the translation process is not completed and then all empty translations have to be deleted again. Thus, they should only be created when the finished xliff is imported again.

**Comment by melegiul** [comment]
>     * Show new icon for translations if the `currently_in_translation` flag is set (to make sure it is not shown as "outdated" anymore)

So when I understand right, that means we just want to update state "outdated" -> "in process", that means actually setting the "currently_in_translation" field in database. But for all "non-existing" translations we want to "ignore" the xliff export in terms of currently_in_translation flag. Is this right?

**Comment by timoludwig** [comment]
Yes, exactly.
