### ISSUE TITLE
Preview for live content

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#619]
### Motivation

At the moment, the aggregated content of a page including live/mirrored content can not be previewed.

### Proposed Solution

Add a possibility to preview the live/mirrored content at its specified position in combination with the original content

### Alternatives

Already implement #496 if feasible for the feature completion milestone

### Additional Context

This has a higher priority than the improved general preview (issue #496), because the wysiwyg editor already shows a rough preview of the normal content field.

**Comment by melegiul** [comment]
I'm not sure if I got this right, so lets say I got page X and I set page Y as live-content after page X. When I now click the preview button ("eye icon"), then there supposed to be page X followed by page Y in the preview. Is this right?

**Comment by timoludwig** [comment]
> I'm not sure if I got this right, so lets say I got page X and I set page Y as live-content after page X. When I now click the preview button ("eye icon"), then there supposed to be page X followed by page Y in the preview. Is this right?

yes, correct.
