### ISSUE TITLE
Add table sorting

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#624]
### Motivation

At the moment, only the event list can be sorted.

### Proposed Solution

Add the same [tablesort](https://www.npmjs.com/package/tablesort) functionality to all our tables:

- [x] Events
- [x] Archived Events
- [x] POIs
- [x] Archived POIs
- [ ] Regions
- [ ] Languages
- [ ] Admin Users
- [ ] Region Users
- [ ] Organizations
- [ ] Offer Templates
- [ ] Admin Feedback
- [ ] Region Feedback
- [ ] Push Notifications

**Comment by ulliholtgrave** [comment]
No longer needed. See #885
