### ISSUE TITLE
Add possibility to refresh `last_updated` date

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#629]
### Motivation

If region managers want to refresh the changed date to make sure the page doesn't look outdated to the users when in fact it isn't, they have to change anything in the content to make the form save. Otherwise the form is not saved with the message "No changes detected" or similar. 

### Proposed Solution

~Add the possibility to update the date without changing the content.~
~E.g. Show the last update date and a button "Refresh" next to it, which changes the date to the current moment.~

### Alternatives

Make it possible to submit the form without changes to update the date. 
Adapt the message to show something like "No changes detected, but date updated" or similar.

### Additional Context

Optionally add a bulk action to update the changed date of all selected pages

**Comment by svenseeberg** [comment]
I vote for the alternative. I think we should keep the buttons to a minimum. One alternative I can think of: We could change the caption of the "Save" button. For example if no changes were made. the caption is "Refresh Date", and if changes were made, the caption changes to "Save changes". Something like that.

**Comment by timoludwig** [comment]
Ok. I think changing the title of the "save"-button might be confusing, but I think it should be clear what happens when we adapt the success message which is shown.

**Comment by MizukiTemma** [comment]
I think, too, it is confusing if the button is renamed (the editor may think they cannot change the page contents anymore when they see "Refresh date" but no "update") and more intuitiv to refresh the date is clicking update/aktuasilieren (not renamed button) without any change.

Shall I even so let the buttun name be changing depend on there is any change on the page?

**Comment by MizukiTemma** [comment]
P.S. After clicking update without change the refresh confirmation message will be shown. I thinki this is necessary.
