### ISSUE TITLE
Page saving message not correct

### ISSUE THREAD

**Issue by melegiul** [Integreat/integreat-cms#635]
### Describe the Bug

Wrong information message when editing live/mirrored content of pages

### Steps to Reproduce

1. Go to regions page menu and select a page
2. Add some live/mirrored content to the page
3. Publish/save changes
4. The message says no changes were made

### Expected Behavior

Message should confirm, that changes were successfully saved.

### Actual Behavior

No changes were detected

### Additional Information

This bug only concerns the displayed message, nevertheless live/mirrored content is saved correctly to database and also shows up in the populated form.

**Comment by timoludwig** [comment]
This problem seems to be related to #466.
