### ISSUE TITLE
Move GUI language switcher to user settings menu

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#651]
### Motivation
We have two different "languages": one for the content and one for the admin back end UI. This needs to be cleanly separated to not confuse users. In #630 we want to improve the languages switcher. However, I see a danger of confusing a language switcher with the GUI language switcher. And I think that it is almost never necessary for a user to switch the language. This frequently confuses even me in WordPress / WPML.

### Proposed Solution
The user GUI language option/setting should be moved to the user settings, and be removed from the top navigation bar.

### Alternatives
Keep as is or move it into the expandable user menu.

**Comment by timoludwig** [comment]
Possible options:
1. Store the language setting on a browser-cookie-basis (as it is in the moment) and just change the location of the switcher
    - Pro: less effort
    - Con: setting not preserved over multiple devices
2. Add a new field to the user profile model, store the setting in the database and after each login, [explicitly set the active language](https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#explicitly-setting-the-active-language)
    - Pro: setting preserved over multiple devices
    - Con: more effort

**Comment by melegiul** [comment]
I would vote for option 1 and keeping the browser-cookie-basis as is, that should be sufficient.
