### ISSUE TITLE
Convert datetime according to user's timezone

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#652]
### Motivation

Our server's timezone (currently set to "UTC") does not necessarily correspond to the user's timezone. Thus, we have to convert every `datetime` input & output in the templates to local time.

### Proposed Solution

First problem: How to get the user's timezone?

  - ~Option A: Deriving from the language setting (bad, because it is ambiguous e.g. for English)~
  - Option B: Add another field to the user settings to store the timezone
  - Option C: Use geolocation services to automatically derive the user's timezone, e.g.:
    - [django-tz-detect](https://pypi.org/project/django-tz-detect/)
    - [django-easy-timezones-redux](https://pypi.org/project/django-easy-timezones-redux/)
    - [django-visitor-information-middleware](https://pypi.org/project/django-visitor-information-middleware/)

Second problem: How to convert the datetime?

  - https://docs.djangoproject.com/en/2.2/topics/i18n/timezones/
  - https://tommikaikkonen.github.io/timezones/

### Alternatives

If we make the assumption that all our users are located in the Central European Time (CET) timezone, we just can set the server time to CET and don't need further adjustments. However, this will not suffice in the long term.

### Additional Context

We also have to think about what to do with events:

  - Option A: Store event time in the server's timezone
    - Convert input value before writing it into the database
    - Convert datetime whenever it gets printed ot delivered via the API
  - Option B: Store event time in the event's local time
    - Do not convert input value on saving
    - Do not convert datetime on output
    - Can we assume creator's timezone == event's timezone?

**Comment by Thomas125** [comment]
Is there always a canonical event's local time?
For example, regarding a zoom-meeting of some german people with some australian people. What is the event's local time?
Is this relevant for us?

**Comment by melegiul** [comment]
I would also prefer Option B, as the django docs suggest [selecting-current-timezone](https://docs.djangoproject.com/en/2.2/topics/i18n/timezones/#selecting-the-current-time-zone), it's common practice to save a local timezone to each user profile. That will keep our timestamps internally as "UTC", but formats the output according to users local timezone. However this does not address the problem about events timezones. Per default events should inherit their timezone from the creators user profile, maybe extended with some further customization options, e.g. "Select a custom timezone for this event"-button.

**Comment by Thomas125** [comment]
Is it possible to use the timezone of the end user's computer?

**Comment by timoludwig** [comment]
>* Is there always a canonical event's local time?
>    * For example, regarding a zoom-meeting of some german people with some australian people. What is the event's local time?
>    * Is this relevant for us?
>* And there is always the thing with the daylight saving time

I'm not entirely sure, but for the sake of "cleanliness" I'd prefer the same solution for all timestamps in the database - so UTC timestamps also for events and not the local time, even if I think that international zoom sessions are not in the scope of the event model.

>* Option A (Deriving time zone from language) is not a good solution. The time zone is rather independent of the used language.

Yes, I agree.

> I would also prefer Option B, as the django docs suggest [selecting-current-timezone](https://docs.djangoproject.com/en/2.2/topics/i18n/timezones/#selecting-the-current-time-zone), it's common practice to save a local timezone to each user profile. That will keep our timestamps internally as "UTC", but formats the output according to users local timezone. However this does not address the problem about events timezones. Per default events should inherit their timezone from the creators user profile, maybe extended with some further customization options, e.g. "Select a custom timezone for this event"-button.

Sounds good to me.

> Is it possible to use the timezone of the end user's computer?

In theory, yes. It involves a bit of geolocation services which I don't think we necessarily need (because we don't have anonymous users) and I'd like to avoid these services... but I updated the issue description and listed a few possible solutions for option C.

**Comment by svenseeberg** [comment]
IMHO we should keep the concept of time zones away from users and potentially even the CMS. We can assume (for now) that all users are in the same timezone. That means that all user input datetimes can be taken "as is" (UTC). Only system-generated times are an issue, for example save page timestamps. That can be solved by setting one timezone for the CMS in the settings.py.

**Comment by svenseeberg** [comment]
I think the solution should be the following: we set a time zone in the config (or read it from the OS time zone). Additionally, there is a setting that toggles between "single time zone" and "multiple time zones" mode. For now, we need only a single time zone. If someone is motivated to implement this now, then okay. Otherwise I'd say "Additional Features" milestone.
