### ISSUE TITLE
Improve menu bar

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#682]
### Proposed Solution

- Change the order of the menu items so it corresponds to the current order in wordpress
- Apply consistent capitalization (rule 2 from https://www.grammarbook.com/punctuation/capital.asp)

### Additional Context

![Screenshot_2021-02-22 Dashboard ‹ Testumgebung — WordPress](https://user-images.githubusercontent.com/16021269/108729278-a4ddaf00-752a-11eb-918d-8db13181f5ce.png)

**Comment by ulliholtgrave** [comment]
Additionally, We should rename the menu-item "Push-Benachrichtungen" to "Nachrichten"
