### ISSUE TITLE
Set default permissions for staff members

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#684]
### Proposed Solution

Staff members should be granted permissions to manage all network resources, except:

- Delete regions
- Delete languages
- Delete organization
- Delete offer templates
- Delete roles
- Delete users

**Comment by melegiul** [comment]
I've looked a bit in the documentation and I found that the staff field of user object is just a boolean, which allows to enter the built-in django admin site ([django:staff](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/#django.contrib.auth.models.User.is_staff)). So I would propose two steps to address this issue:
1. Create a role named staff to assign all permission except for the above listed ones. At the moment our roles are defined in the file `cms.fixtures.roles.json` so I could append this staff role to this file.
2. Assign this role to users, which enable the staff checkbox in the admin user form.

So do I understand this issue right or is there another recommended approach?

**Comment by timoludwig** [comment]
> So do I understand this issue right or is there another recommended approach?

Yes, I think this is the correct way to go. We have to think about one problem though: We don't want to make it possible to assign non-staff users to this special role. And I don't think we should hardcode this role to be excluded from the set of normal roles etc...
So I thought maybe it's best to create a new model with a onetoone field to the original `Group` model (similar to the `User` and `UserProfile` models) where we store the information which roles are meant for staff members and which aren't... This way, we can also add multiple roles for staff members if we need to add more fine-graded access control.
I started with this idea on the branch [feature/staff-roles](https://github.com/Integreat/integreat-cms/tree/feature/staff-roles) (see commit 5a23a5b5343b550c14cdc7837d74c5f3d1a53ff6 "Add support for staff and non-staff roles"), so if you think this makes sense, you can start your work off of this branch.

**Comment by melegiul** [comment]
I didn't know that you already working on this issue and you made quite some progress. So you introduce a new boolean field to the group model to indicate that staff role has some special meaning, makes sense to me. Feel free to go ahead, until now I have not written any code yet.

**Comment by timoludwig** [comment]
> I didn't know that you already working on this issue and you made quite some progress. So you introduce a new boolean field to the group model to indicate that staff role has some special meaning, makes sense to me. Feel free to go ahead, until now I have not written any code yet.

No, I haven't been working on it before you commented, I just wanted to try out my idea yesterday to see if it works... Not that I suggest something which doesn't 😄
I didn't mean to steal the issue from you, if you want to continue, feel free to do so 😉

**Comment by melegiul** [comment]
No, you have not stolen the issue, my idea was just a basic role addition, while your solution already covers some further extensions like access restriction, role grouping, etc., which we might need in future anyway :smile:
