### ISSUE TITLE
Improve revision view

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#692]
### Motivation

The revision slider needs further adjustments:

### Proposed Solution

- Make slider less wide (about 1/2 - 3/4)
- Move "Back to editor"-button right beneath heading
- Show author of version in tool tip
- Rename "Revision" to "Version"

**Comment by MizukiTemma** [comment]
![image](https://user-images.githubusercontent.com/82345046/117640809-b592de00-b185-11eb-840b-d23a69f16342.png)

Which is meant as the width of the slider, A or B?

**Comment by timoludwig** [comment]
It's the width A. The whole width of the slider should not go across the whole page. So in theory, it should be enough to change `w-full` [here](https://github.com/Integreat/integreat-cms/blob/db018a4d01af2f2d1cff20d94fcbf641942077aa/src/cms/templates/pages/page_revisions.html#L20) to e.g. `w-3/5` and add the class `m-auto`.
