### ISSUE TITLE
Improve event form

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#694]
### Proposed Solution

- [ ] Move status and version to the top right corner (see #691)
- [x] Switch labels for end-date and end-time
- [x] Add german translation of "Erstelle einen Veranstaltungsort oder beginne den Namen eines bestehenden Veranstaltungsortes einzutippen." to "Erstellen Sie einen Veranstaltungsort oder beginnen Sie den Namen eines bestehenden Veranstaltungsortes einzutippen."
- [ ] Add checkbox "Event does not have a physical location" and only show location fields if checkbox is not checked
- [ ] Fix the poi ajax query for the non-staff-users (verwaltung, event planner are getting 403 here)
- [ ] On change of start-date and start-time, copy the value into end-date and end-time if they are empty
- [x] Remove minor edit field
- [ ] Use the same dynamic slug/link update mechanism like for pages

**Comment by ulliholtgrave** [comment]
A good first approach to that issue is the page_form template, which includes a lot of the desired UI changes.
