### ISSUE TITLE
Improve user list & form

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#696]
### Proposed Solution

List:

- Add role column
- ~Show email incl. email verified field~

Form:

- Fix translation of "Roles" label
- Make multi roles select field to single select
- Make role obligatory for non-superuser users

**Comment by ulliholtgrave** [comment]
Files that need adjustments are:
src/cms/templates/users/region/list.html (Create new roles / email verified columns)
src/cms/templates/users/region/list_row.html (Load user data in new columns)
src/cms/models/users/user_profile.py (To adjust the property of the roles for a user)
src/cms/forms/users/user_form.py (Adjust user fields & **Translation**)
src/cms/models/users/user_profile.py (Adjust user field)
