### ISSUE TITLE
Move offer selection to region form

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#699]
### Proposed Solution

Move the offer page to the region form. Change the selection e.g. to checkboxes. Optionally, we could simplify the models here by removing the offer model and adding a manytomany field to the region model where the offer templates can be selected.

**Comment by melegiul** [comment]
When I understand this right, then this issue would consists of the following steps:

1. Remove the menu "Offers", currently located at the region specific sites
2. This menu mainly allows to activate offers, so this offer activation should be available in the region form, located at the network management site

The "offer template" menu + corresponding form should stay as it is (currently also on network management site)
Is this right?

**Comment by timoludwig** [comment]
> When I understand this right, then this issue would consists of the following steps:
> 
>     1. Remove the menu "Offers", currently located at the region specific sites
> 
>     2. This menu mainly allows to activate offers, so this offer activation should be available in the region form, located at the network management site
> 
> 
> The "offer template" menu + corresponding form should stay as it is (currently also on network management site)
> Is this right?

Yes, correct.

Regarding the idea of simplifying the models in the proposed solution above: I'm not sure if I thought this through, but in theory I think we could remove the Offer model (since all it stores in the database is a mapping from regions to offer templates), but we'd have to move the logic of the properties somewhere... either into the region model or we leave it as class which can be instantiated (but is not saved to the database)... since I didn't try it out yet, I'm not sure which of both works best... do you have any thoughts on this?

**Comment by timoludwig** [comment]
Another possibility would be to move the functionality of transforming `OfferTemplate` objects to `Offer` objects right into the [Offer API](https://github.com/Integreat/integreat-cms/blob/develop/src/api/v3/offers.py). Since the information about Offers isn't needed anywhere else in the CMS, this also sounds like a valid option to me.
