### ISSUE TITLE
Enhancement for rss feed icon

### ISSUE THREAD

**Issue by melegiul** [Integreat/integreat-cms#724]
### Motivation

Reshape the rss feed icon to meet the origins wordpress shape. 

### Proposed Solution

Currently the rss feed icon is in a smaller cube shape, to make it more similar to its origin wordpress version it should be added rounded corners and the size should be increased.

### Alternatives

Keep it as it is.

### Original wordpress rss feed icon

![rssfeed](https://user-images.githubusercontent.com/47010475/109797372-ab021880-7c19-11eb-9f94-b52e6c239deb.png)

**Comment by timoludwig** [comment]
Just for reference: The further adjustments of the RSS feed are tracked in  #687.
