### ISSUE TITLE
GVZ API client not working anymore

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#796]
### Describe the Bug

Since the GVZ API server changed recently, our GVZ API client doesn't work anymore:
```
Apr 26 18:05:17 INFO gvz_api.apps - GVZ API is not available. You won't be able to automatically import coordinates and region aliases.
```

### Steps to Reproduce

1. Start development server
4. See GVZ API logging message

### Expected Behavior

The GVZ API is available, so it should be recognized as available
### Actual Behavior

The GVZ API server is mistakenly recognized as down

### Additional Information

If interacting with the GVZ API is a common task for other use cases, it could also make sense to outsource our gvz api client to a separate repository and distribute it as pip package.

**Comment by svenseeberg** [comment]
Sorry, and thanks for creating this issue. Just wanted to do this :-)
