### ISSUE TITLE
Not possible to create new push Notification Channels

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/integreat-cms#810]
### Describe the Bug
For new and existing regions it is not possible to add new or any Firebase channels at all.

### Steps to Reproduce

1. Go to 'Regions'
2. Click on 'any region'
3. Add a new channel to the list 'Push Notification Channels'
4. Enter the Region and open "Messages"
5. Try to select a channel

### Expected Behavior
The channel should appear in the drop-down

### Actual Behavior
Channel isn't there.

### Additional Information
There is no new Channel Object created in the database either.

**Comment by timoludwig** [comment]
Not relevant anymore due to #813.
