### ISSUE TITLE
Menu links not working anymore when media library is opened

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#877]
### Describe the Bug

When the media library is opened, all other links outside the media library are not working anymore and are just interpreted as directory ids for the media library.
E.g., when clicking on the link http://localhost:8000/admin_dashboard/, the preact router catches this URL and actually opens http://localhost:8000/media-library/#/admin_dashboard/, which causes the server error `ValueError: Field 'id' expected a number but got 'admin_dashboard'` and the in the frontend, the error `An error has occurred. Please try again later.` appears.

### Steps to Reproduce

1. Go to the media library
2. Click on any link outside the media library

### Expected Behavior

Normal links should still work

### Actual Behavior

All links are treated as internal media library links of the preact router

**Comment by ulliholtgrave** [comment]
This seems to be only a problem, when we are in the admin view of the library. The Preact component seems to call the directory content API everytime a link is clicked.
