### ISSUE TITLE
Merge `User` and `UserProfile` models to custom `User` model

### ISSUE THREAD

**Issue by timoludwig** [Integreat/integreat-cms#878]
### Motivation

In the beginning of the project, we thought that we'd only need a few customizations to the User model, so we added the `UserProfile` model for these additional fields. In the meantime however, the custom functionality grew and it has become more and more difficult to handle user objects and their respective profiles.

### Proposed Solution

Merge `User` and `UserProfile` models to custom `User` model with one centralized validation method.
The [documentation](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#substituting-a-custom-user-model) provides a very detailed guide on what to look out for.

### Alternatives

Keep the current setup

### Additional Context

[According to the docs](https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project), changing to a custom user model in mid-project is significantly more difficult than doing it beforehand, because migrating existing user data is hard. So although this is not 100% required for the version 1.0 release, I put it in this milestone because we should try to finish this before the release.

**Comment by svenseeberg** [comment]
#859 requires a custom user model, therefore this issue should probably be solved first.
