### ISSUE TITLE
Media library breaks Back End links

### ISSUE THREAD

**Issue by svenseeberg** [Integreat/integreat-cms#901]
### Describe the Bug
After opening the media library, it is not possible to navigate out of it.

### Steps to Reproduce

1. Open the admin media library
2. Click `Admin Dashboard`
3. An error message `An error has occurred. Please try again later.` appears. The network history tells us that the browser tried to load `/ajax/media/directory-path?directory=admin_dashboard` as an AJAX request instead of opening `/admin_dashboard` in the main window.

I guess that some JS is overstepping its competencies ;)

**Comment by timoludwig** [comment]
Is this a duplicate of #877?

**Comment by svenseeberg** [comment]
It is.
