### ISSUE TITLE
Add cache for calculated values

### ISSUE THREAD

**Issue by ulliholtgrave** [Integreat/integreat-cms#944]
### Motivation
Depends on #942 
We want to load some of the calculated values (e.g. current_translation of a page) directly into the Redis cache

**Comment by timoludwig** [comment]
We should stick to inbuilt Django functionality as much as possible, thus anyone working on this issue should first read:

- https://docs.djangoproject.com/en/3.2/ref/utils/#django.utils.functional.cached_property
- https://docs.djangoproject.com/en/3.2/topics/cache/#basic-usage
- https://github.com/Suor/django-cacheops#usage

**Comment by membralala** [comment]
Right now  I think, that there is not very much potential in using djangos cached properties. Database query optimization is pretty well done by redis-cacheops and the case, where the same model instance has to do heavy computation multiple times, so I'll close this issue for now.
